input_data_path: "data/train.csv"
output_solution: "models/model1.pkl"
output_metrics: "metrics/metrics.json"
splitting_params:
  test_size: 0.3
  random_state: 123
model_params:
  model_type: "KNeighborsClassifier"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_feature:
    - "condition"